### ISSUE TITLE
默认icon,和过期时间处理问题

### ISSUE THREAD

**Issue by TangHui123** [tianzhijiexian/ShareLoginLib#10]
你好，请问一下，第一次登录调到三方登录界面的，默认显示的 icon 怎么是 app 字样的图片。怎么处理过期的问题。

**Comment by kaleai** [comment]
这个icon是无法控制的，过期时间一般不用处理。

**Comment by TangHui123** [comment]
QQ登录和微博登录的scope的值填什么。。。 “get_userinfo”？？？么

**Comment by TangHui123** [comment]
W/System.err: org.json.JSONException: No value for nickname
04-19 16:34:28.938 24497-24497/? W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
04-19 16:34:28.938 24497-24497/? W/System.err:     at org.json.JSONObject.getString(JSONObject.java:550)

QQ登录成功后，获取nickname失败。。。请问有遇到过么

**Comment by TangHui123** [comment]
I change the QQ  scope "get_userinfo" to "get_simple_userinfo" and the question is solved.  TKS

**Comment by magical-xu** [comment]
@TangHui123 请问这样改了之后 还是报上面那个错是什么原因？ 是不是 getQQUserInfo方法里请求的那个地址不对啊？要换成 https://openmobile.qq.com/user/get_simple_userinfo这个

**Comment by kaleai** [comment]
可以做如下的配置：

```
QQ_SCOPE = "get_user_info,"
                + "get_simple_userinfo,"
                + "add_share,"
                + "add_topic,"
                + "add_pic_t";
```
