### ISSUE TITLE
要是能加上 Facebook 和 Twitter 就好了

### ISSUE THREAD

**Issue by Puppy-Love** [tianzhijiexian/ShareLoginLib#12]

**Comment by kaleai** [comment]
未来会开放成platform的形式支持更多的平台，可以允许使用者自行扩展第三方平台。facebook等平台在库层面不会支持，但你可以用库未来提供的接口很方便的接入它们。

这个工作目前已经在进行了，等搭建好了后欢迎提交pr，：）
