### ISSUE TITLE
登录 好像这里内存泄露了

### ISSUE THREAD

**Issue by Puppy-Love** [tianzhijiexian/ShareLoginLib#13]
![image](https://user-images.githubusercontent.com/16749976/30534678-d61f5f8e-9c91-11e7-8b57-4c56436cb042.png)

**Comment by kaleai** [comment]
这个应该是activity中静态引用有问题了，我看一下。

**Comment by kaleai** [comment]
@Puppy-Love 是毕现的么，这时候是否已经收到的登录的回调。这里貌似是腾讯的sdk持有了activity的引用，可以看下是否是毕现的，谢啦。

**Comment by kaleai** [comment]
已经修复
