### ISSUE TITLE
关于SlConfig的使用问题

### ISSUE THREAD

**Issue by wimwu** [tianzhijiexian/ShareLoginLib#14]
关于这些配置是否有更好的方法来实现？因为在程序初始化时它是作为一个静态变量保存在那里的，占用着内存，可能存在内存泄漏，而且这些配置除了分享的时候其它的情况下都是不需要的

**Comment by kaleai** [comment]
可以讨论一下这个点。但配置的静态string对于性能和内存方面的影响是可以忽略不计的，欢迎有更好的思路
