### ISSUE TITLE
可以更新SDK到最新的嘛

### ISSUE THREAD

**Issue by ljackChen001** [tianzhijiexian/ShareLoginLib#15]
可以更新SDK到最新的嘛

**Comment by kaleai** [comment]
呀，目前它们又升级了？你需要哪个呢，说明下版本我看看

**Comment by kaleai** [comment]
@ljackChen001 你指的是微博的sdk么？

**Comment by ljackChen001** [comment]
是啊

**Comment by kaleai** [comment]
@ljackChen001 微博4.0的sdk坑太多了，给我几天时间，更新好了则会关闭此问题

**Comment by kaleai** [comment]
@ljackChen001 目前已经完成升级，但新版本的sdk问题比较多，所以需要跑自动化测试和monkey，等待测试完毕后会发布新版本并通知您。

顺便一问，目前的库能否正常使用，集成方面有无问题？

**Comment by kaleai** [comment]
已经更新
