### ISSUE TITLE
关于qq,微博的scope

### ISSUE THREAD

**Issue by GuoYangGit** [tianzhijiexian/ShareLoginLib#17]
您好，我在第三方平台并没有找到相关的scope说明，您能给个链接或者讲解下么

**Comment by kaleai** [comment]
scope就是说这个app需要请求的数据范围是什么。

qq文档中的说明，可以在其文档中通过ctrl+f查找scope字段进行了解:

http://wiki.open.qq.com/index.php?title=Android_API%E8%B0%83%E7%94%A8%E8%AF%B4%E6%98%8E&=45038

![image](https://user-images.githubusercontent.com/9552155/49161967-e3448d80-f364-11e8-86fb-e61c4a2111a9.png)

微博的文档：

![image](https://user-images.githubusercontent.com/9552155/49162343-a75df800-f365-11e8-8533-708027bd5522.png)

https://github.com/sinaweibosdk/weibo_android_sdk

http://open.weibo.com/wiki/%E7%A7%BB%E5%8A%A8%E5%BA%94%E7%94%A8%E4%BB%8B%E7%BB%8D

**Comment by GuoYangGit** [comment]
谢谢作者的回复
