### ISSUE TITLE
新浪微博的配置你配置错了，详细的可以看新浪sdk的源码

### ISSUE THREAD

**Issue by Lyon1994** [tianzhijiexian/ShareLoginLib#9]
截图贴不出来了，在SL_WeiBoHandlerActivity.java的大概60到70行之间
你把appKey配置成了appID，

**Comment by Lyon1994** [comment]
WeiboShareSDK.createWeiboAPI（）这个函数好像也是的

**Comment by kaleai** [comment]
这里的appKey其实就是appId，因为qq和微信都是叫做appId，而微博叫做appKey，是个笔误。

可以暂时忽略命名的问题，此外此项目中应该没有WeiboShareSDK.createWeiboAPI()这个代码吧。
